<?php
/**
 * @author         Vladimir Popov
 * @copyright      Copyright (c) 2015 Vladimir Popov
 */

/** @var VladimirPopov\WebForms\Block\Form $this */
//For paypal notify url
/*Changed by MD for cancel handling process[START][02-05-2019]*/
$helper = $this->helper('SIT\MainAdmin\Helper\Data');
$objectManager = \Magento\Framework\App\ObjectManager::getInstance();
$storeManager = $objectManager->get('\Magento\Store\Model\StoreManagerInterface');
$baseUrl = $storeManager->getStore()->getBaseUrl(\Magento\Framework\UrlInterface::URL_TYPE_WEB);
$mediaUrl = $helper->getPubMedia();
$paymentMode = $block->paymentModeConfig();
$paypalEmail = $block->paypalEmailConfig();
$post_id_chk_col_id = '';

if($this->getRequest()->getParam('web_en')) {
    $web_en = $this->getRequest()->getParam('web_en');
    $encode_url_str = base64_decode(urldecode($web_en));
    $str_explode = explode('||', $encode_url_str);
    $form_id = $str_explode[0];
    $post_form_id = $str_explode[1];
    $post_id_chk_col = $block->getResultId($post_form_id);
    $post_id_chk_col_id = $post_id_chk_col;
}
if($post_id_chk_col_id) {
    if($post_form_id) {
        $webform_fields_col=$block->getFieldsData($form_id,$post_form_id);
        $_uid = $this->getUid();
    ?>
    <html>
        <body>
        <div id="paypal_cancel_form_custom">
            <h3><?= $this->getForm()->getName(); ?></h3>
            <form action="<?php echo $this->getFormAction() ?>" method="post" name="webform_<?php echo $form_id ?>" id="webform_<?php echo $form_id ?>"  enctype="multipart/form-data" class="form">
                 <input name="form_key" type="hidden" value="<?php /* @escapeNotVerified */
                    echo $this->getFormKey() ?>"/>
                <input type="hidden" name="submitWebform_<?php echo $form_id ?>" value="1"/>
                <input type="hidden" name="webform_id" value="<?php echo $form_id ?>"/>
                <input type="hidden" id="delivery_price" name="delivery_price" value=""/>
                <input type="hidden" name="payment_mode" value="<?php echo $paymentMode?>"/>
                <input type="hidden" name="paypal_email" value="<?php echo $paypalEmail?>"/>
                <input type="hidden" name="post_data_id" value="<?php echo $post_form_id?>"/>
                <input type="hidden" name="ret_url" value="<?php echo strtok($block->currentUrl(),'?');?>?webform_id=<?php echo $form_id ?>"/>
                <table cellspacing="5" cellpadding="5" align='center'>
                    <?php
                    foreach ($webform_fields_col as $key => $value) {
                      if(!($value->getCode() == 'express_delivery' || $value->getCode() == 'delivery_method' || $value->getCode() == 'amount' || $value->getCode() == 'payment_confirmed' || $value->getCode() == 'transaction_id')){
                            if($value->getCode() == 'Country'){$country_val = $value['value']['text'];}
                            if($value->getValue() != "")
                            {?>
                                <tr width="50%" align='center'>
                                    <td align='right' width="30%" style="color:#696868">
                                        <?php
                                                echo $value->getName()."   :    ";
                                        ?>
                                        <?php if($value->getName() == "Purchase date (dd.mm.yyyy)"):
                                            $date= date_create($value['value']['text']);
                                            $final_date = date_format($date,"M j, Y");
                                        ?>
                                        <input type="hidden" id="<?php echo $value->getName();?>" name="field[<?php echo $value->getFieldId();?>]" value="<?php echo $final_date;?>">
                                        <?php else: ?>
                                        <input type="hidden" id="<?php echo $value->getName();?>" name="field[<?php echo $value->getFieldId();?>]" value="<?php echo $value['value']['text'];?>">
                                    <?php endif; ?>
                                    </td>
                                    <td align='left' width="30%">
                                        <?php echo $value['value']['text']; ?>
                                    </td>
                                </tr>
                            <?php
                            }
                         }
                         if(($value->getCode() == 'express_delivery' || $value->getCode() == 'delivery_method' || $value->getCode() == 'amount' || $value->getCode() == 'payment_confirmed' || $value->getCode() == 'transaction_id')){
                                ?>
                                <input type="hidden" id="<?php echo $value->getCode();?>" name="field[<?php echo $value->getFieldId();?>]" value="<?php echo $value['value']['text'];?>">
                            <?php
                         }
                    }
                    ?>
                    <input type="hidden" id="count_code" value="<?php echo $country_val;?>"/>
                    <tr>
                    <td style="color:#696868" width="30%" align="right"><?php echo __('Express Delivery'); ?> :</td>
                    <td>
                        <div class="control">
                            <input type="radio" class="required-entry" name="delivery_form" value="Yes" id='express_yes'> Yes
                            <input type="radio" class="required-entry" name="delivery_form" value="No" id='express_no'> No
                        </div>
                    </td>
                    </tr>
                    <tr width="50%" align='right'>
                    <td id="td_del_method" style="display:none;color:#696868" width="30%" align="right"><?php echo __('Delivery Method'); ?> :</td>
                    <td align='left' width="30%">
                        <div id="div_country_price"  class="dv_country_price_cancel form-row" name="div_country_price" style="display:none;">
                            <br/>
                        </div>
                        </td>
                    </tr>
                </table>
                <center>
                    <div class="primary">
                        <button type="submit" class="form_button sp_btn_submit action submit primary"
                                    id="webform_submit_button"
                                    title="<?php echo __('submit') ?>">
                            <span>
                                <span id='sp_form_button'><?php echo __('Submit') ?></span>
                            </span>
                        </button>
                    </div>
                    <div class="secondary">
                        <div class="please-wait" id="webform_<?php echo $form_id ?>_sending_data"
                             style="display:none;">
                            <div class="loading-indicator"></div>
                            <span id="webform_<?php echo $form_id ?>_progress_text"><?php echo __('Sending...') ?></span>
                        </div>
                    </div>
                </center>
            </form>
        </div>
            <script type="text/javascript">
                require(['jquery', 'jquery/ui'], function($) {
                    jQuery.fn.toHtml=function(){
                       return jQuery(this).html(jQuery(this).text())
                    }
                    jQuery( "#webform_<?php echo $form_id ?>" ).submit(function( event ) {
                      event.preventDefault();
                      jQuery.ajax({
                            type: jQuery( "#webform_<?php echo $form_id ?>" ).attr('method'),
                            url: jQuery( "#webform_<?php echo $form_id ?>" ).attr('action'),
                            data: jQuery( "#webform_<?php echo $form_id ?>" ).serialize(),
                            dataType : 'html',
                            success: function (data) {
                                jQuery(window).scrollTop(120);
                                var obj = jQuery.parseJSON(data);
                                jQuery('#paypal_cancel_form_custom').html(obj.success_text);
                                jQuery('#paypal_cancel_form_custom ul').css('display','none');
                                /*if(jQuery("#paypal_cancel_form_custom ul li a").text() == "" ||  jQuery("#paypal_cancel_form_custom ul li a").text() == null) {
                                    jQuery('.custom-tab-title').text("Sent");
                                } else {
                                    jQuery('.custom-tab-title').text(jQuery("#paypal_cancel_form_custom ul li a").text());
                                }*/
                                // jQuery('#paypal_cancel_form_custom').toHtml();
                            },
                            error: function (data) {
                                console.log('An error occurred.');
                            },
                        });
                    });
                });
            </script>
        </body>
    </html>
        <?php
            //In case redirect fails
            if ($this->getRegistry()->registry('redirect_url')) {
            ?>
            <meta http-equiv="refresh" content="0;url=<?php echo $this->getRegistry()->registry('redirect_url') ?>">
            <script type="text/javascript">
                window.location = '<?php echo $this->getRegistry()->registry('redirect_url')?>';
            </script>
            <?php
        }
    }
}
/*Changed by MD for cancel handling process[END][02-05-2019]*/
else {
        if(array_key_exists('payment_status', $_POST)) {
            if($_POST['payment_status']=="Completed")
            {
                $req = 'cmd=_notify-validate';
                // Assign posted variables to local variables
                $data['item_name']          = $_POST['item_name'];
                $data['item_number']        = $_POST['item_number'];
                $data['payment_status']     = $_POST['payment_status'];
                $data['payment_amount']     = $_POST['mc_gross'];
                $data['payment_currency']   = $_POST['mc_currency'];
                $data['txn_id']             = $_POST['txn_id'];
                $data['receiver_email']     = $_POST['receiver_email'];
                $data['payer_email']        = $_POST['payer_email'];
                $data['custom']             = $_POST['custom'];
                $data['invoice']            = $_POST['invoice'];
                $data['paypallog']          = $req;

                $webform_payment_conf = $block->getFieldsConf($_GET['webform_id']);
                $field_transaction_id="";
                $field_payment_confirmed="";
                foreach ($webform_payment_conf as $key => $value)
                {
                    if($value['code']=="payment_confirmed")
                    {
                        $field_payment_confirmed=$key;
                    }
                    if($value['code']=="transaction_id")
                    {
                        $field_transaction_id=$key;
                    }
                }
                $writeConnection = $block->resourceConnect();
                if($data['payment_status']=="Completed" && $data['txn_id']!="")
                {
                    $query_up_pay = "UPDATE webforms_results_values set value='Yes' where result_id=".$data['item_number']." and (field_id=$field_payment_confirmed)";
                    $writeConnection->query($query_up_pay);
                    $query_up_tr = "UPDATE webforms_results_values set value='".$data['txn_id']."' where result_id=".$data['item_number']." and (field_id=$field_transaction_id)";
                    $writeConnection->query($query_up_tr);
                }
            }
        }
        //For paypal return url
        if(isset($_GET['st']))
        {
            if($_GET['st']=="Completed")
            {
                $fields = $block->getFieldsConf($_GET['webform_id']);
                $result = $block->getItemNumber($_GET['item_number']);

                $webform_model = $block->getWebformData($_GET['webform_id']);
                $webform_model->sendFormMail($result,$fields);
                $paypal_status=$_GET['st'];
                $tx_id=$_GET['tx'];

                $webform_payment_conf = $block->getFieldsConf($_GET['webform_id']);
                $field_transaction_id="";
                $field_payment_confirmed="";
                foreach ($webform_payment_conf as $key => $value) {
                    if($value['code']=="payment_confirmed")
                    {
                        $field_payment_confirmed=$key;
                    }
                    if($value['code']=="transaction_id")
                    {
                        $field_transaction_id=$key;
                    }
                }
                $writeConnection = $block->resourceConnect();
                $query_up_pay = "UPDATE webforms_results_values set value='Yes' where result_id=".$_GET['item_number']." and field_id=$field_payment_confirmed";
                $writeConnection->query($query_up_pay);
                $query_up_tr = "UPDATE webforms_results_values set value='".$tx_id."' where result_id=".$_GET['item_number']." and field_id=$field_transaction_id";
                $writeConnection->query($query_up_tr);
            }
        }
    //In case redirect fails
    if ($this->getRegistry()->registry('redirect_url')) {
        ?>
        <meta http-equiv="refresh" content="0;url=<?php echo $this->getRegistry()->registry('redirect_url') ?>">
        <script type="text/javascript">
            window.location = '<?php echo $this->getRegistry()->registry('redirect_url')?>';
        </script>
        <?php
    }
    // Get temporary data
    $tmpData = $this->getSession()->getData('webform_result_tmp_' . $this->getForm()->getId());
    $tmpResult = new \Magento\Framework\DataObject;
    $_uid = $this->getUid();
    if (!empty($tmpData['field']) && is_array($tmpData['field'])) {
        foreach ($tmpData['field'] as $field_id => $value) {
            $tmpResult->setData('field_' . $field_id, $value);
        }
    }
    if ($this->getForm()->getIsActive() == \VladimirPopov\WebForms\Model\Form::STATUS_DISABLED || !$this->isDirectAvailable()) {
        echo $this->getNotAvailableMessage();
    } else { ?>

        <?php if ($this->isAjax()) { ?>
            <div id="webform_<?php echo $_uid ?>_success_text" class="std webforms-success-text"
                 style="display:none"></div>
        <?php } ?>

        <?php
        if ($this->getSuccess()) {
            ?>
            <div class="webforms-success-text">
                <?php echo $this->getSuccessText() ?>
            </div>
            <?php
        }
        if(isset($_GET['st'])) {
            if($_GET['st']=="Completed")
            {
                $fields = $block->getFieldsConf($_GET['webform_id']);
                $result = $block->getItemNumber($_GET['item_number']);
                $webform_model=$block->getWebformData($_GET['webform_id']);
                $webform_model->sendFormMail($result,$fields);
                ?>
                 <div class="std webforms-success-text">
                    <ul class='tabs'>
                    <li id='cur_category' class='active first'><a href='javascript:void(0)'> <?php echo __('Success'); ?> </a></li>
                    </ul>
                        <div class='section-inner-presse-page'>
                        <p>
                        <?php echo __('Payment process completed.<br/>Thank you very much for your order. We will process your request as soon as possible and notify you upon shipment.'); ?>
                        </p>
                        </div>
                </div>
            <?php
            }
        }
        else if ($this->getRegistry()->registry('show_success')) {
            ?>
            <div class="std webforms-success-text">
                <?php
                $fields = $block->getFieldsConf($_GET['webform_id']);
                $result = $block->getItemNumber($_GET['item_number']);
                $webform_model=$block->getWebformData($_GET['webform_id']);
                $webform_model->sendFormMail($result,$fields);
                echo $this->getWebform()->getSuccessText() ?>
            </div>
        <?php
        } else {

            if ($messages = $this->getErrorMessages()) : ?>
                <div class="message error">
                    <div>
                        <?php foreach ($messages as $message): ?>
                            <?php /* @escapeNotVerified */
                            echo $message ?><br/>
                        <?php endforeach; ?>
                    </div>
                </div>
            <?php endif; ?>

            <?php
            $aria_describedby = "";
            if ($this->getDescription()) {
                $aria_describedby = "aria-describedby=\"{$_uid}form_description\"";
            }

            ?>
            <div id="webform_<?php echo $_uid ?>_form" class="webforms"<?php echo $aria_describedby ?>>
                <!-- <div class="form-title-main">
                    <h3>
                        <span class="form-title-span"><?= $this->getForm()->getName(); ?></span>
                    </h3>
                </div> -->
                <?php if ($this->getDescription()) { ?>
                    <div id="<?php echo $_uid ?>form_description" class="webforms-description-text">
                        <?php echo html_entity_decode($this->getDescription()); ?>
                    </div>
                <?php } ?>

                <?php if ($this->isAjax()) { ?>
                    <iframe title="<?php echo $this->getForm()->getName()?>"
                            id="webform_<?php echo $_uid ?>_iframe"
                            name="webform_<?php echo $_uid ?>_iframe"
                            role="none"
                            style="width:0;height:0;border:0;position:absolute"></iframe>
                <?php } ?>

                <form class="form" action="<?php echo $this->getFormAction() ?>" method="post"
                      name="webform_<?php echo $_uid ?>"
                      id="webform_<?php echo $_uid ?>" enctype="<?php echo $this->getEnctype() ?>"
                      class="webforms-<?php echo $this->getForm()->getCode() ?>"
                      aria-describedby="<?php echo $_uid ?>form_description"
                      aria-label="<?php echo $this->getForm()->getName() ?>"
                      <?php if ($this->isAjax()) { ?>target="webform_<?php echo $_uid ?>_iframe"<?php } ?> role="none">

                    <input name="form_key" type="hidden" value="<?php /* @escapeNotVerified */
                    echo $this->getFormKey() ?>"/>
                    <input type="hidden" name="submitForm_<?php echo $this->getForm()->getId() ?>" value="1"/>
                    <input type="hidden" name="submitWebform_<?php echo $this->getForm()->getId() ?>" value="1"/>
                    <input type="hidden" name="webform_id" value="<?php echo $this->getForm()->getId() ?>"/>
                    <input type="hidden" name="payment_mode" value="<?php echo $paymentMode?>"/>
                    <input type="hidden" name="paypal_email" value="<?php echo $paypalEmail?>"/>
                    <input type="hidden" name="ret_url" value="<?php echo strtok($block->currentUrl(),'?');?>?webform_id=<?php echo $this->getForm()->getId() ?>"/>

                    <?php if (is_array($this->getData('hidden'))) {
                        foreach ($this->getData('hidden') as $key => $value) {
                            ?>
                            <input type="hidden" name="<?php echo $key ?>" value="<?php echo $value ?>"/>
                            <?php
                        }
                    } ?>

                    <?php if (count($this->getForm()->_getHidden())) {
                        foreach ($this->getForm()->_getHidden() as $field) {
                            echo $field->toHtml();
                        }
                    } ?>
                    <script type="text/javascript">
                        var company_id='';
                    </script>
                    <?php foreach ($this->getForm()->_getFieldsToFieldsets() as $fieldset_id => $fieldset) { ?>

                        <fieldset id="fieldset_<?php echo $_uid . $fieldset_id ?>"
                             class="fieldset fieldset-<?php echo $fieldset_id ?> <?php if (!empty($fieldset['css_class'])) echo $fieldset['css_class']; ?>"
                             style="<?php if (!empty($fieldset['css_style'])) echo $fieldset['css_style'].";"; ?><?php if ($fieldset['logic_visibility'] == \VladimirPopov\WebForms\Model\Logic::VISIBILITY_HIDDEN) echo 'display:none'; ?>"
                             role="group" aria-labelledby="legend_<?php echo $_uid . $fieldset_id ?>">

                            <?php if (!empty($fieldset['name'])) { ?>
                                <h3 class="legend" id="legend_<?php echo $_uid . $fieldset_id ?>">
                                    <span><?php echo $fieldset['name'] ?></span></h3><br>
                            <?php } ?>

                            <?php
                            foreach ($fieldset['fields'] as $field) {
                                //Set temporary value
                                $field->setData('result', $tmpResult);
                                $field->setData('uid', $_uid);
                                $field_css_type = 'type-' . str_replace('/', '-', $field->getType());
                                if ($field->getType() == 'subscribe') $field_css_type .= ' choice';
                                $aria_labelledby = "aria-labelledby=\"label_field" . $this->getFieldUid($field->getId()) . "\"";
                                if (in_array($field->getType(), array("html", "subscribe")))
                                    $aria_labelledby = "";
                                $label_for = "for=\"field" . $this->getFieldUid($field->getId()) . "\"";
                                if (in_array($field->getType(), array("select/radio", "select/checkbox"))) {
                                    $label_for = "";
                                }

                                $aria_describedby = "";
                                if ($field->getComment()) $aria_describedby = "aria-describedby=\"comment_field" . $this->getFieldUid($field->getId()) . "\"";
                                ?>
                                <!-- Changed by MD for set global variable values[START][01-05-2019] -->
                                <?php
                                    if($field->getCode()=="express_delivery")
                                    {   ?>
                                        <script type="text/javascript">
                                            var Express_Delivery='<?php echo $field->getId(); ?>';
                                        </script>
                                        <?php
                                    }
                                    /*Changed by MD for set default focus in company field[START][11-10-2019]*/
                                    if($field->getCode()=="Company")
                                    {   ?>
                                        <script type="text/javascript">
                                            var company_id='<?php echo $field->getId(); ?>';
                                        </script>
                                        <?php
                                    }
                                    /*Changed by MD for set default focus in company field[END][11-10-2019]*/
                                    if($field->getCode()=="delivery_method")
                                    {   ?>
                                        <script type="text/javascript">
                                            var Delivery_Method='<?php echo $field->getId(); ?>';
                                        </script>
                                        <?php
                                    }
                                    if($field->getCode()=="amount")
                                    {   ?>
                                        <script type="text/javascript">
                                            var Delivery_Amount='<?php echo $field->getId(); ?>';
                                        </script>
                                        <?php
                                    }
                                    if($field->getCode()=="payment_confirmed")
                                    {   ?>
                                        <script type="text/javascript">
                                            var Payment_Confirmed='<?php echo $field->getId(); ?>';
                                        </script>
                                        <?php
                                    }
                                    if($field->getCode()=="transaction_id")
                                    {   ?>
                                        <script type="text/javascript">
                                            var Transaction_Id='<?php echo $field->getId(); ?>';
                                        </script>
                                        <?php
                                    }
                                ?>
                                <!-- Changed by MD for set global variable values[END][01-05-2019] -->
                                <div id="field_<?php echo $field->getId() ?>" role="group"
                                     class="field <?php echo $field->getCssClassContainer() ?> <?php echo $field_css_type ?> webforms-fields-<?php echo $field->getId() ?><?php if ($field->getCode()) { ?> webforms-fields-<?php echo $field->getCode();
                                     } ?> <?php if ($field->getRequired()) { ?>required<?php } ?>"
                                    <?php echo $aria_labelledby ?>
                                    <?php echo $aria_describedby ?>
                                    <?php if ($field->getData('logic_visibility') == \VladimirPopov\WebForms\Model\Logic::VISIBILITY_HIDDEN) echo 'style="display:none"'; ?>>

                                    <?php if ($field->getType() != 'html' && $field->getType() != 'subscribe' && !$field->getHideLabel()) {
                                        if($field->getCode() != "express_delivery" && $field->getCode() != "delivery_method" && $field->getCode() != "amount" && $field->getCode() != "payment_confirmed" && $field->getCode() != "transaction_id") { ?>
                                        <label class="label webform-label"
                                               id="label_field<?php echo $this->getFieldUid($field->getId()) ?>"
                                            <?php echo $label_for ?>>
                                            <?php if($field->getCode() == 'product_batch_code') { 
                                                $batchUrl = $baseUrl."where-can-i-find-the-production-batch-code";
                                            ?>
                                            <a href="<?php echo $batchUrl; ?>" class="dotted_link" target="_blank"><?php echo $field->getName(); ?> </a>
                                            <?php } else {
                                                echo $field->getName();
                                            }?> 
                                            <?php
                                            $tooltip = $field->getTooltip();
                                            if ($tooltip) {
                                                echo $this->getLayout()->createBlock(
                                                    'VladimirPopov\WebForms\Block\Script\Tooltip',
                                                    null
                                                )->setField($field)->setTooltip($tooltip)->toHtml();
                                            }
                                            ?>
                                        </label>

                                    <?php }} ?>

                                    <div class="control" role="group" <?php echo $aria_labelledby ?>>
                                        <?php echo $field->toHtml(); ?>

                                        <?php if ($field->getValidationAdvice()) { ?>
                                            <div style="display:none" class="validation-advice"
                                                 id="advice-required-entry-field<?php echo $this->getFieldUid($field->getId()) ?>">
                                                <?php echo $field->getValidationAdvice() ?>
                                            </div>
                                        <?php } ?>

                                        <?php if ($field->getComment()) { ?>
                                            <?php if($field->getType() == "subscribe") { ?>
                                            <p class="webforms-fields-comment"
                                               id="comment_field<?php echo $this->getFieldUid($field->getId()) ?>"
                                               tabindex="0">
                                                <?php echo nl2br($field->getComment()) ?>
                                            </p>
                                        <?php } else {?>
                                            <div class="tool-tip"></div>
                                            <div class="tooltip-content help"
                                                 id="comment_field<?php echo $this->getFieldUid($field->getId()) ?>">
                                                 <?php echo nl2br($field->getComment()) ?>
                                            </div>
                                        <?php
                                            }
                                        }
                                        ?>
                                    </div>

                                </div>
                            <?php } ?>
                        </fieldset>

                    <?php } // foreach 'fields_to_fieldsets' ?>

                    <div class="webform-gdpr-agree">
                    <?php
                    echo $this->getLayout()->createBlock('Magento\Cms\Block\Block')->setBlockId('newsletter_gdpr_agreement')->toHtml();
                    ?>
                    </div>
                    <?php echo $this->getLayout()->createBlock(
                        'VladimirPopov\WebForms\Block\Script\Gdpr',
                        null,
                        ['data' => [
                            'uid' => $_uid
                        ]]
                    )->setForm($this->getForm())->toHtml();
                    ?>
                    <!-- Changed by MD for Express Delivery[START][30-04-2019] -->
                    <div class="form-row" >
                        <?php
                        $is_express=$this->getForm()->getUseExpressDelivery();
                        if($is_express)
                        {
                             echo $this->getLayout()->createBlock(
                                'Magento\Framework\View\Element\Template',
                                null,
                                [
                                    'data' => [
                                        'webform_id' => $this->getForm()->getId(),
                                        'template' => 'VladimirPopov_WebFormsDepend::webforms/fields/delivery.phtml'
                                    ]
                                ]
                            )->toHtml();
                        }
                        ?>
                    </div>
                    <!-- Changed by MD for Express Delivery[END][30-04-2019] -->
                    <div id="submit<?php echo $_uid?>" class="actions-toolbar" <?php if($this->getSubmitVisibility() == 'hidden'){?>style="display: none"<?php }?>>
                        <?php if ($this->getForm()->useCaptcha()) { ?>
                            <div class="recaptcha">
                                <?php echo $this->getCaptcha()->getHTML() ?>
                            </div>
                        <?php } ?>

                        <?php if ($this->honeypot()) {
                            /*echo $this->getLayout()->createBlock(
                                'Magento\Framework\View\Element\Template',
                                null,
                                [
                                    'data' => [
                                        'webform_id' => $this->getForm()->getId(),
                                        'template' => 'VladimirPopov_WebForms::webforms/scripts/honeypot.phtml'
                                    ]
                                ]
                            )->toHtml();*/
                        } ?>
                        <p class="required required-fields">* Required Fields</p>
                        <div class="primary">
                            <button type="submit" class="action submit primary"
                                    id="webform_<?php echo $_uid ?>_submit_button"
                                    title="<?php echo __($this->getForm()->getSubmitButtonText()) ?>"
                                    name="field[submit]">
                                <!-- Changed by MD for submit button[id='sp_form_button'][START][01-05-2019] -->
                                <span id='sp_form_button'><?php echo __($this->getForm()->getSubmitButtonText()) ?></span>
                                <!-- Changed by MD for submit button[id='sp_form_button'][END][01-05-2019] -->
                            </button>
                        </div>
                        <div class="secondary">
                            <div class="please-wait" id="webform_<?php echo $_uid ?>_sending_data"
                                 style="display:none;">
                                <div class="loading-indicator"></div>
                                <span id="webform_<?php echo $_uid ?>_progress_text"><?php echo __('Sending...') ?></span>
                            </div>
                        </div>
                    </div>

                </form>
                <!-- Changed by MD for Footer Description[START][26-04-2019] -->
                <?php if ($this->getForm()->getFooterDescription()) { ?>
                    <div id="<?php echo $_uid ?>form_footer_description" class="webform-footer-desc">
                        <?php echo html_entity_decode($this->getForm()->getFooterDescription()); ?>
                    </div>
                <?php } ?>
                <!-- Changed by MD for Footer Description[END][26-04-2019] -->
            </div>
            <?php echo $this->getLayout()->createBlock(
                'VladimirPopov\WebForms\Block\Script\Submit',
                null,
                ['data' => [
                    'uid' => $_uid,
                    'ajax' => $this->isAjax(),
                    'scroll_to' => $this->getData('scroll_to'),
                    'after_submission_form' => $this->getData('after_submission_form')
                ]]
            )->setForm($this->getForm())->toHtml();
            ?>

            <?php echo $this->getLayout()->createBlock(
                'VladimirPopov\WebForms\Block\Script\Logic',
                null,
                ['data' => [
                    'uid' => $_uid
                ]]
            )->setForm($this->getForm())->toHtml();
            ?>
            <?php
        } // if(show_success)
    } // is active
}//else completed
/*Changed by MD for invoice_address_change_request web-form[START][02-07-2019]*/
if($this->getForm()->getCode() == 'invoice_address_change_request') { ?>
    <script type="text/javascript">
        function checkOrderData(orderNr) {
             jQuery.ajax({
             url: "<?php echo $this->getUrl("webformdepend/form/ordernumber"); ?>",
             type: "post",
             data: {order_number:orderNr},
             success: function (data) {
                var orderData = data.replace(/"/g, '');

                if(orderData == "Order not found" || orderData == "Number length incorrect!") {
                       jQuery(".order_img").css("display", "none");
                       jQuery(".order_error").css("display", "block");
                       jQuery('#orderNum').val(orderNr);
                } if(orderData == "Order found " + orderNr) {
                       jQuery(".order_error").css("display", "none");
                       jQuery(".order_img").css("display", "block");
                       jQuery('#orderNum').val('');
                } if(orderData == "Wrong argument!") {
                       jQuery(".order_error").css("display", "none");
                       jQuery(".order_img").css("display", "none");
                }
               }
             });
        }
    </script>
<?php }
/*Changed by MD for invoice_address_change_request web-form[END][02-07-2019]*/
?>
<script type="text/javascript">
    function checkVatNumber(Obj,vatNumber)
    {
        if(vatNumber.trim() != ""){
            var countryCode = vatNumber.substring(0, 2);
            var baseUrl = "<?php echo $baseUrl; ?>"+"vat/example.php";
            jQuery.ajax({
                url: baseUrl,
                type: "post",
                data: {vat_number:vatNumber,country_code:countryCode},
                dataType:"json",
                success: function (data) {
                    jQuery('div.webforms-fields-Company input').val('');
                    jQuery('div.webforms-fields-Company input').val(data['business_name']);
                    jQuery('div.webforms-fields-Street input').val('');
                    jQuery('div.webforms-fields-Street input').val(data['address']);
                    jQuery('div.webforms-fields-Country select.webform-field-country-select').val('');
                    jQuery('div.webforms-fields-Country select.webform-field-country-select').val(data['member_state']).find("option[value=" + data['member_state'] +"]").attr('selected', 'selected');
                    var field_id = jQuery(Obj).attr('id');
                    if(data['validation'] == 0){
                        jQuery("#vat_img_"+field_id).css("display", "none");
                        jQuery("#vat_error_"+field_id).css("display", "block");
                        jQuery("#vat_error_message_"+field_id).css("display", "block");
                        jQuery(".tooltip-content.help").addClass('help-error');
                    } else {
                        jQuery("#vat_img_"+field_id).css("display", "block");
                        jQuery("#vat_error_"+field_id).css("display", "none");
                        jQuery("#vat_error_message_"+field_id).css("display", "none");
                        jQuery(".tooltip-content.help").removeClass('help-error');
                    }
                }
            });
        }

    }
</script>
<script>
require(['jquery', 'jquery/ui'], function($) {
    function ajaxReq(){
        if(jQuery("input[name='post_data_id']").val() == undefined) {
            window.localStorage.setItem("delivery_method_data",null);
        }
        var country_code = jQuery("#count_code").val();
        var i = 1;
        jQuery.ajax({
            url: "<?php echo $this->getUrl("webformapi/country/country"); ?>",
            type: "post",
            data:{country:country_code},
            success: function(country_data) {
                var data = jQuery.parseJSON(country_data);
                var radioHTML="";
                jQuery("#div_country_price").html("");
                jQuery.each(data, function( key, value ) {
                        if(value.price!="0.00") {
                            i++;
                            radioHTML = "<input type='radio'  name='rdo_shipping' data-value="+value.price+" id='rdo_shipping"+i+"' value='"+value.delivery_type+"'"+"  "+">";
                            radioHTML += "<div class='express_delivery_image_div'><img class='express_delivery_image' src='" + "<?php echo $mediaUrl; ?>" + value.ship_icon + "' name='ship_icon'/></div><div class='express_delivery_duration'><span>" + value.delivery_duration + " " + "<?php echo __('days')?></span></div><div class = 'express_delivery_price'><span> €" + value.price + "</span></div><br/>";

                            jQuery("#div_country_price").css("display","block");
                            jQuery("#td_del_method").css("display","block");
                            jQuery("#div_country_price").append(radioHTML);
                            jQuery("#sp_form_button").text('Pay and submit');
                            if(window.localStorage.getItem("delivery_method_data") == null || window.localStorage.getItem("delivery_method_data") == "null") {
                                jQuery('input:radio[value="'+jQuery("#delivery_method").val()+'"]').attr('checked',true);
                            } else {
                                jQuery('input:radio[value="'+window.localStorage.getItem("delivery_method_data")+'"]').attr('checked',true);
                            }
                            if(jQuery("input[name='rdo_shipping']").length > 0 ) {
                                jQuery("#delivery_price").val(jQuery('input[type=radio][name=rdo_shipping]:checked').attr('data-value'));
                                jQuery('input[type=radio][name=rdo_shipping]').change(function(){
                                    jQuery("#delivery_method").val(jQuery('input[type=radio][name=rdo_shipping]:checked').val());
                                    jQuery("#delivery_price").val(jQuery('input[type=radio][name=rdo_shipping]:checked').
                                        attr('data-value'));
                                    jQuery("#amount").val(jQuery('input[type=radio][name=rdo_shipping]:checked').attr('data-value'));
                                    window.localStorage.setItem("delivery_method_data", jQuery("#delivery_method").val());
                                });
                            }
                            jQuery(".sp_btn_submit").click(function(){
                                jQuery(".please-wait").css("display","block");
                            });
                        } else {
                            jQuery("#sp_form_button").text('Submit');
                            jQuery("#div_country_price").css("display","none");
                            jQuery("#td_del_method").css("display","none");
                            jQuery("#sp_form_button").text('Submit');
                        }
                });
            }
        });
    }
    jQuery(document).ready(function() {
        if(jQuery('#paypal_cancel_form_custom').length == 0) {
            if(company_id) {
                var cmp_id = "field["+company_id+"]";
                jQuery('input[name='+'"'+cmp_id+'"'+']').focus();
            }
        }
        jQuery("#express_yes").attr('checked',true);
        if(jQuery("#express_yes").prop('checked')) {
            jQuery("#express_delivery").val("Yes");
            jQuery("#payment_confirmed").val("No");
            jQuery("#transaction_id").val("0");
        }
        ajaxReq();
    });
    jQuery("input[name='delivery_form']").change(function() {
        if(jQuery("#express_yes").prop('checked')) {
            jQuery("#express_delivery").val("Yes");
            jQuery("#payment_confirmed").val("No");
            jQuery("#transaction_id").val("0");
            ajaxReq();
        }
        if(jQuery("#express_no").is(':checked')) {
            jQuery("#express_delivery").val("");
            jQuery("#delivery_method").val("");
            jQuery("#amount").val("");
            jQuery("#payment_confirmed").val("");
            jQuery("#transaction_id").val("");
            jQuery("#div_country_price").css("display","none");
            jQuery("#td_del_method").css("display","none");
            jQuery("#sp_form_button").text('Submit');
        }
    });
});
</script>