<?php
/**
 * Copyright © MageKey. All rights reserved.
 * See LICENSE.txt for license details.
 */

/** @var \Magento\Store\Block\Switcher $block */
$_dataHelper = $this->helper(\MageKey\StoresFlags\Helper\Data::class);
?>
<?php if (count($block->getStores())>1): ?>
<?php $id = $block->getIdModifier() ? '-' . $block->getIdModifier() : '' ?>
<div class="switcher language switcher-language" data-ui-id="language-switcher" id="switcher-language<?= /* @noEscape */ $id ?>">
    <strong class="label switcher-label"><span><?= $block->escapeHtml(__('Language')) ?></span></strong>
    <div class="actions dropdown options switcher-options">
        <div class="action toggle switcher-trigger"
             id="switcher-language-trigger<?= /* @noEscape */ $id ?>"
             data-mage-init='{"dropdown":{}}'
             data-toggle="dropdown"
             data-trigger-keypress-button="true">
            <strong class="view-<?= $block->escapeHtml($block->getCurrentStoreCode()) ?>">
                <?php if ($currentFlag = $_dataHelper->getCurrentFlag()): ?>
                <span class="flag-icon flag-icon-<?= /* @noEscape */ $currentFlag ?>"></span>
                <?php else: ?>
                <span><?= $block->escapeHtml($block->getStoreName()) ?></span>
                <?php endif; ?>
            </strong>
        </div>
        <ul class="switcher-dropdown"
            data-target="dropdown">
            <?php foreach ($block->getStores() as $_lang): ?>
                <li class="view-<?= $block->escapeHtml($_lang->getCode()) ?> switcher-option<?= /* @noEscape */ ($_lang->getFlag() ? ' has-flag' : '') ?>">
                    <a href="#" data-post='<?= /* @noEscape */ $block->getTargetStorePostData($_lang) ?>'>
                        <?php if ($_lang->getFlag()): ?>
                            <span title="<?= $block->escapeHtml($_lang->getName()) ?>" class="flag-icon flag-icon-<?= /* @noEscape */ $_lang->getFlag() ?>"></span>
                        <?php endif; ?>
                        <?php if ($_lang->getId() == $block->getCurrentStoreId()): ?>
                            <span class="language-code active"><?= $block->escapeHtml($_lang->getCode()) ?></span>
                        <?php else: ?>
                            <span class="language-code"><?= $block->escapeHtml($_lang->getCode()) ?></span>
                        <?php endif; ?>
                    </a>
                </li>
            <?php endforeach; ?>
        </ul>
    </div>
</div>
<?php endif; ?>