<?php

namespace Qsoft\NewsletterCustom\Block\Subscription;

class Unsubscriber extends \Magento\Framework\View\Element\Template
{
    /**
     * @var \Magento\Framework\UrlInterface
     */
    protected $urlInterface;

    /**
     * @var \Magento\Newsletter\Model\Subscriber
     */
    protected $subscriber;

    public function __construct(
        \Magento\Framework\View\Element\Template\Context $context,
        \Magento\Framework\UrlInterface $urlInterface,
        \Magento\Newsletter\Model\Subscriber $subscriber
    )
    {
        $this->urlInterface = $urlInterface;
        $this->subscriber = $subscriber;

        parent::__construct($context);
    }

    /**
     * @return array
     */
    public function getInfoLink()
    {
        $params = $this->getRequest()->getParams();
        return $params;
    }

    /**
     * @return string
     */
    public function getBaseUrl()
    {
        return parent::getBaseUrl(); // TODO: Change the autogenerated stub
    }

}