<?php
/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */

/**
 * Code standard by : Rh [1-3-2019]
 */
$page = "";
$limitUrlParam = "";
if ($this->getRequest()->getParam("p")) {
    $page = $this->getRequest()->getParam("p");
}
if ($this->getRequest()->getParam("limit")) {
    $limitUrlParam = $this->getRequest()->getParam("limit");
}
?>

<div data-bind="scope: 'sitGeneralnews'">
    <!-- ko template: getTemplate()  -->
    <!-- /ko  -->
</div>

<script type="text/x-magento-init">
{
    "*":{
        "Magento_Ui/js/core/app":{
            "components": {
                "sitGeneralnews":{
                    "component":"SIT_GeneralNews/js/kogeneralnews",
                    "controller_url":"<?= $block->getUrl("generalnews/news/kogeneralnews");?>",
                    "pageNumber":"<?= $page?>",
                    "limitUrlParam":"<?= $limitUrlParam?>",
                    "imgloader":"<?= $block->getViewFileUrl('images/loader-1.gif') ?>"
                }
            }
        }
    }
}
</script>