<?php

/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */

/**
 * Code standard by : Rh
 */

/** @var $block \SIT\LanguageTranslator\Block\Adminhtml\Locale\Options\Labels  */
$translateId = $this->getParams();
$translateData = $block->getPost();

$sID = [];

if ($translateId == null) {
    $translateData = $block->getStores();
} else {
    $translateData = $translateData;
}
if ($translateData == null) {
    $translateData = $block->getStores();
}

?>

<div class="fieldset-wrapper admin__collapsible-block-wrapper opened sit_storebox" id="manage-titles-wrapper">
    <div class="fieldset-wrapper-content in collapse" id="manage-titles-content">
        <fieldset class="admin__fieldset fieldset">
            <div class="admin__control-table-wrapper">
                <table class="admin__control-table" id="attribute-labels-table">
                    <thead>
                        <tr>
                            <?php foreach ($block->getStores() as $_store) :
                                array_push($sID, $_store->getId());
                            ?>
                                <th class="col-store-view"><?= /* @escapeNotVerified */ $_store->getName() ?></th>
                            <?php endforeach; ?>
                        </tr>
                    </thead>
                    <tbody>
                        <tr>
                            <?php foreach ($translateData as $_store) : ?>
                                <?php if ($translateId == null) { ?>
                                    <td class="col-store-view">
                                        <textarea class="input-text<?php if ($_store->getId() == \Magento\Store\Model\Store::DEFAULT_STORE_ID) : ?> required-option<?php endif; ?>" data-form-part="languagetranslator_form" name="frontend_label[<?= /* @escapeNotVerified */ $_store->getId() ?>]" <?php if ($block->getReadOnly()) : ?> data-validate="{required:true}" disabled="disabled" <?php endif; ?>></textarea>
                                    </td>
                                    <?php } else {
                                    if (in_array($_store['store_id'], $sID)) {

                                    ?>
                                        <td class="col-store-view">
                                            <textarea class="input-text<?php if ($_store['store_id'] == \Magento\Store\Model\Store::DEFAULT_STORE_ID) : ?> required-option<?php endif; ?>" data-form-part="languagetranslator_form" data-validate="{required:true}" name="frontend_label[<?= /* @escapeNotVerified */ $_store['store_id']; ?>]" <?php if ($block->getReadOnly()) : ?> disabled="disabled" <?php endif; ?>><?php echo trim($_store['translated_string']); ?></textarea>
                                        </td>
                                <?php }
                                }
                                ?>
                            <?php endforeach; ?>
                        </tr>
                    </tbody>
                </table>
            </div>
        </fieldset>
    </div>
</div>
<style type="text/css">
    .sit_storebox textarea.input-text {
        width: 100%;
        height: 200px;
    }
</style>