<?php
/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */

/**
 * Code standard by : Rh [1-3-2019]
 */
?>
<?php
	$faqData = $block->getFaqCategoryData();
?>
<?php foreach ($faqData as $faqkey => $faq): ?>
<div class="clist std">
	<h2><?= $faq['category_name'] ?></h2>
	<?php foreach ($faq['products'] as $key => $value): ?>
		<a class="ptitle dotted_link" href="<?= $value['product_url'] ?>"><?= $value['product_name'] ?></a><br>
	<?php endforeach; ?>
	<?php if(isset($faq['redirect_url']) && $faq['redirect_url'] != ""):?>
		<a class="ptitle faqitalic dotted_link" href="<?= $faq['redirect_url'] ?>"><?php echo __('general FAQs').' ('.__($faq['category_name']).') ';?></a></a><br>
	<?php endif; ?>
</div>
<?php endforeach; ?>
<p class="contents faq-post-text">
<?php echo __('Do you have a question concerning one of our products? Please use <strong><a class="dotted_link" href="' . $block->getBaseUrl().'contact' . '">this form </a></strong> to pose a question!','');?>
</p>
