<?php
/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */

/**
 * Code standard by : Rh [1-3-2019]
 */
?>


<div class="complist-cpu custom-scroller">
	<div class="section-inner-presse-page-full">
		<div class="complist-cpu-pretext">
			<?php
				$cpu_comp = $this->getLayout()->createBlock('Magento\Cms\Block\Block')->setBlockId('cpu_compatibility_pretext')->toHtml();
				echo substr($cpu_comp,0,strpos($cpu_comp,'{{cpu_compatibility}}'));
			?>
		</div>
		<span data-bind="scope: 'sitCompCategoryViewCpu'">
			<!-- ko template: getTemplate()  -->
			<!-- /ko  -->
		</span>
		<div class="complist-cpu-bottom">
			<?php echo $this->getLayout()->createBlock('Magento\Cms\Block\Block')->setBlockId('comp_cpu_bottom_text')->toHtml(); ?>
		</div>
	</div>
</div>

<script type="text/x-magento-init">
{
	"*":{
		"Magento_Ui/js/core/app":{
			"components": {
				"sitCompCategoryViewCpu":{
					"component":"SIT_ProductCompatibility/js/category/view/supportcompcpu",
					"controllerUrl":"<?= $block->getUrl('sit_productcompatibility/category/compcpu');?>"
				}
			}
		}
	}
}
</script>