<?php
/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */

/**
 * Code standard by : Rh [1-3-2019]
 */
?>
<div class="comp-socket custom-scroller">
	<div class="section-inner-presse-page-full">
		<div class= "comp-socket-desc">
            <?= $this->getLayout()->createBlock('Magento\Cms\Block\Block')->setBlockId('socket_compatibility_chart_pretext')->toHtml();?>
        </div>
		<span id="sit-comp-socket-chart-data">
            <?= $this->getLayout()->createBlock('Magento\Cms\Block\Block')->setBlockId('socket_compatibility_chart')->toHtml();?>
        </span>
	</div>
</div>