<?php
	$sitHelper = $this->helper('SIT\MainAdmin\Helper\Data');
	$currentProduct = $sitHelper->getCurrentProduct();
	$currentProductId = $currentProduct->getId();
	$gridType = 'CPU';
	$sitProdHelper = $this->helper('SIT\ProductCompatibility\Helper\Data');
	$collectionSize = $sitProdHelper->getCollectionSize($gridType,$currentProductId);
	$prod_comp_block = $this->getLayout()->createBlock('Magento\Cms\Block\Block')->setBlockId('cpu_compatibility_pretext')->toHtml();
	$cpu_description = '';
	if($currentProduct->getResource()->getAttribute('cpu_compatibility_pretext')){
		$cpu_description = $currentProduct->getResource()->getAttribute('cpu_compatibility_pretext')->getFrontend()->getValue($currentProduct);
	}
	if ($collectionSize > 0):
?>
<div class="product-service-cpucomp-content custom-scroller">
	<div class="cpucomp-inner-container">
		<div class="cpucomp-content">
			<?php echo str_replace("{{cpu_compatibility}}",$sitHelper->getCmsFilterContent(trim($cpu_description)),$sitHelper->getCmsFilterContent(trim($prod_comp_block)));
			?>
		</div>
		<!-- ko scope: 'sitCompProductViewCompCpu' -->
			<!-- ko template: getTemplate()  -->
			<!-- /ko  -->
		<!-- /ko  -->
		<div class="cpu-bottom-content">
			<?php echo $this->getLayout()->createBlock('Magento\Cms\Block\Block')->setBlockId('comp_cpu_bottom_text')->toHtml(); ?>
		</div>
	</div>
</div>

<script type="text/x-magento-init">
{
	"*":{
		"Magento_Ui/js/core/app":{
			"components": {
				"sitCompProductViewCompCpu":{
					"component":"SIT_ProductCompatibility/js/product/view/compcpu",
					"controllerUrl":"<?= $block->getUrl('sit_productcompatibility/products/compcpu');?>",
					"currentProductId":<?= $currentProductId; ?>
				}
			}
		}
	}
}
</script>
<?php endif;?>
